# Server Port
server.port=8082

# Spring Application Name
spring.application.name=entrance-cockpit-backend

# --- Kafka Consumer ---
spring.kafka.consumer.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=cockpit-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=upec.badge.entrance_cockpit_backend.dto,upec.badge.core_operational_backend.model

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Topic name
kafka.topic.access-events=${KAFKA_ACCESS_EVENTS_TOPIC:access-events}

# --- MQTT Publisher ---
mqtt.broker.host=${MQTT_HOST}
mqtt.broker.port=${MQTT_PORT}
mqtt.client.id=EntranceCockpitBackend_Manual
mqtt.topic.manual-control=iot/door/manual

# For SSE endpoint
spring.mvc.async.request-timeout=-1

# Core backend URL
app.core-backend.url=${CORE_BACKEND_URL}