# Server Port
server.port=8082

# Spring Application Name
spring.application.name=entrance-cockpit-backend

# Kafka Consumer Configuration
spring.kafka.producer.bootstrap-servers=172.31.252.62:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.consumer.bootstrap-servers=172.31.252.62:9092
spring.kafka.consumer.group-id=cockpit-group
spring.kafka.consumer.auto-offset-reset=earliest
# Configure Kafka to trust our custom DTO package
spring.kafka.consumer.properties.spring.json.trusted.packages=upec.badge.entrance_cockpit_backend.dto,upec.badge.core_operational_backend.model

# JSON Deserializer for our DTO
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Custom Topic Names
kafka.topic.access-events=entrance_logs

# MQTT Publisher Configuration (for manual control)
mqtt.broker.host=172.31.252.62
mqtt.broker.port=1883
mqtt.client.id=EntranceCockpitBackend_Manual
mqtt.topic.manual-control=iot/door/manual

# For the SSE endpoint
spring.mvc.async.request-timeout=-1

app.core-backend.url=http://core-operational-backend:8081