spring.application.name=core-operational-backend
server.port=8081

# --- PostgreSQL ---
spring.datasource.url=jdbc:postgresql://172.31.249.179:5432/badge_db
#spring.datasource.url=jdbc:postgresql://192.168.1.20:5432/badge_db
spring.datasource.username=badge_user
spring.datasource.password=super-secret
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# --- Redis ---
spring.data.redis.host=172.31.249.179
spring.data.redis.port=6379
# spring.cache.type=redis
# -- spring.cache.redis.time-to-live=600000

# --- Kafka ---
spring.kafka.bootstrap-servers=172.31.249.179:9092
# Producer setup
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# Auto topic creation (dev only)
spring.kafka.admin.auto-create=true

