spring.application.name=watchdog-app
server.port=9999

# --- Watchdog config ---
watchdog.target-url=${WATCHDOG_TARGET_URL:http://core-backend-a:8081/status}
watchdog.backup-container=${WATCHDOG_BACKUP_CONTAINER:core-backend-b}
watchdog.check-interval-ms=${WATCHDOG_CHECK_INTERVAL_MS:5000}
