services:
  zookeeper:
    # This is a pre-built, official image. No 'build' step is needed.
    image: confluentinc/cp-zookeeper:${CONFLUENT_VERSION:-7.5.0}
    container_name: badge-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeperdata:/var/lib/zookeeper/data
    networks:
      - messaging-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - messaging-net
    depends_on:
      - zookeeper

  mosquitto:
    # This is a pre-built, official image.
    image: eclipse-mosquitto:${MOSQUITTO_VERSION:-2}
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ../mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquittodata:/mosquitto/data
    networks:
      - messaging-net

  door-lock-mock:
    build:
      context: ../../app/services/iot/door-lock-mock
    container_name: door-lock-mock
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=1883
    networks:
      - messaging-net

  badging-mock:
    build:
      context: ../../app/services/iot/badging-mock
    container_name: badge-lock-mock
    depends_on:
      - mosquitto
    networks:
      - messaging-net

  telemetry-backend:
    build:
      context: ../../app/services/telemetry-messaging-backend
    container_name: telemetry-backend
    environment:
      KAFKA_URL: "kafka:9092"
      MQTT_BROKER_HOST: "mosquitto"
      MQTT_BROKER_PORT: 1883
      MQTT_BADGE: "iot/entrance/badge"
      MQTT_DOOR: "iot/entrance/door"
      KAFKA_BADGE: "entrance_attempts"
      KAFKA_DOOR: "entrance_logs"
    networks:
      - messaging-net
    depends_on:
      - kafka
      - mosquitto
      
volumes:
  zookeeperdata:
  kafkadata:
  mosquittodata:

networks:
  messaging-net:
    driver: bridge
