services:
  zookeeper:
    # This is a pre-built, official image. No 'build' step is needed.
    image: confluentinc/cp-zookeeper:${CONFLUENT_VERSION:-7.5.0}
    container_name: badge-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeperdata:/var/lib/zookeeper/data
    networks:
      - messaging-net

  kafka:
    # This is a pre-built, official image.
    image: confluentinc/cp-kafka:${CONFLUENT_VERSION:-7.5.0}
    container_name: kafka
    ports:
      - "9092:9092"
    env_file: .env
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${MESSAGING_HOST}:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafkadata:/var/lib/kafka/data
    networks:
      - messaging-net
    depends_on:
      - zookeeper

  mosquitto:
    # This is a pre-built, official image.
    image: eclipse-mosquitto:${MOSQUITTO_VERSION:-2}
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ../mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquittodata:/mosquitto/data
    networks:
      - messaging-net

  door-lock-mock:
    build:
      context: ../../app/services/iot/door-lock-mock
    container_name: door-lock-mock
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=1883
    networks:
      - backend
  
  badging-mock:
    build:
      context: ../../app/services/iot/badging-mock
    container_name: badge-lock-mock
    depends_on:
      - mosquitto
    networks:
      - backend

  telemetry-backend:
    build:
      context: ../../app/services/telemetry-messaging-backend
    container_name: telemetry-backend
    environment:
      - KAFKA_URL=kafka
      - MQTT_BROKER_URL=http://localhost
      - MQTT_BROKER_PORT=1883
      - MQTT_BADGE=iot/entrance/badge
      - MQTT_DOOR=iot/entrance/door
      - KAFKA_BADGE=entrance_attempts
      - KAFKA_DOOR=entrance_attempts
    networks:
      - messaging-net
volumes:
  zookeeperdata:
  kafkadata:
  mosquittodata:

networks:
  messaging-net:
    driver: bridge