# Spring Application Name
spring.application.name=cache-loader-backend

# --- CRITICAL ---
spring.main.web-application-type=none

# --- PostgreSQL ---
spring.datasource.url=${DATABASE_URL}

# --- Redis ---
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.cache.type=redis