upstream core-backend {
    server core-operational-backend:8081;
}

upstream cockpit-backend {
    server entrance-cockpit-backend:8082;
}

upstream cockpit_front {
    server badge-cockpit-front:80;
}

server {
    listen 80;

    location = /healthz {
        return 200 "ok";
    }

    # Frontend static assets
    location /assets/ {
        proxy_pass http://cockpit_front;
    }

    # Core backend people API
    location /api/people/ {
        proxy_pass http://core-backend;
    }

    # SSE events stream
    location /api/events {
        proxy_pass http://cockpit-backend;
        proxy_buffering off;        # IMPORTANT for SSE
    }

    # Manual door control
    location /api/manual/ {
        proxy_pass http://cockpit-backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Frontend main UI
    location /cockpit/ {
        rewrite ^/cockpit/(.*)$ /$1 break;
        proxy_pass http://cockpit_front;
    }

    # Root redirect
    location = / {
        return 302 /cockpit/;
    }
}
